[build]
  command = "yarn build"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = '/home#services'
  to = '/'
  status = 200

[[redirects]]
  from = '/contact'
  to = '/'
  status = 200
[[redirects]]
  from = '/redirect'
  to = '/'
  status = 200

[[redirects]]
  from = '/home'
  to = '/'
  status = 200
  force = true 

[[redirects]]
  from = '/*'
  to = '/'
  status = 301
  force = true
