[build]
  command = "yarn build"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = '/home#services'
  to = '/home'
  status = 200

[[redirects]]
  from = '/home/#about'
  to = '/home'
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[redirects]]
  from = '/home'
  to = '/home'
  status = 200
  force = true 

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 301
  force = true
